apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-data-globeco-execution-service-kafka-0
  namespace: globeco
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: "local-storage"  