apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: execution-service-kafka-pvc
  namespace: globeco
  labels:
    app: globeco-execution-service-kafka
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-gp3
  resources:
    requests:
      storage: 10Gi
