apiVersion: v1
kind: Service
metadata:
  name: globeco-execution-service-kafka
  namespace: globeco
  labels:
    app: globeco-execution-service-kafka
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
spec:
  type: ClusterIP
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
  selector:
    app: globeco-execution-service-kafka